### ISSUE TITLE
Use of MiniProfiler causes exception: QueryableValues only works with a SQL Server provider

### ISSUE THREAD

**Issue by micheloliveira-com** [yv989c/BlazarTech.QueryableValues.EF6#15]
Hi, I'm testing this library with MiniProfiler for EF6 (Repo: https://github.com/MiniProfiler/dotnet Nuget: https://www.nuget.org/packages/MiniProfiler.EF6/).
```
   at BlazarTech.QueryableValues.QueryableValuesDbContextExtensions.GetSerializer(DbContext dbContext)
   at BlazarTech.QueryableValues.QueryableValuesDbContextExtensions.AsQueryableValues(DbContext dbContext, IEnumerable`1 values, Boolean isUnicode)
```
It causes the "QueryableValues only works with a SQL Server provider" exception even on v1.1.2 of BlazarTech.QueryableValues.EF6.

Can we have a way to disable this validation?

**Comment by yv989c** [comment]
Hi @michlns , ok. I'll try. I think that for the sake of flexibility it makes sense.

Currently the [logic inside the interceptor](https://github.com/yv989c/BlazarTech.QueryableValues.EF6/blob/68f935927bd7a2f2c97fe5a1017a6f2abc630766/src/QueryableValues.EF6.SqlServer/QueryableValuesCommandInterceptor.cs#LL185C1-L197C14) that makes this work depends on the concrete type `SqlParameter`, which is expected to be the case if the underlying connection is a `SqlConnection`. I'll see if I can achieve the same with `DbParameter` and `DbType` instead of `SqlParameter` and `SqlDbType`. By removing the `SqlConnection` check, if the underlying connection isn't a SQL Server one then the library will still throw a cryptic exception at runtime.

Can you please provide me with more context around how are you using `QueryableValues` with the `MiniProfiler` library?

**Comment by rytmis** [comment]
I just ran into the same issue. What I'm doing is profiling the queries with Entity Framework Profiler and trying to see how using QueryableValues might impact the execution time. The profiler generates wrapper classes that intercept the queries--the underlying connection is still SQL Server, but QueryableValues sees the wrapping type.
